# Source= https://angular.io/guide/testing**//
# Learn yaml file https://www.tutorialspoint.com/yaml/yaml_comments.htm
# Read me: https://gohugo.io/hosting-and-deployment/hosting-on-github/
 
name: Deploy  to Surge

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Node.js (optional if you need npm build, otherwise skip)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install

    # 4️⃣ Build project (if you have a build step)
    - name: Build
      run: npm run build

   # 3️⃣ Install Surge CLI globally
    - name: Install Surge
      run: npm install -g surge

   # 4️⃣ Deploy to Surge
    - name: Deploy
      run: surge ./ ${{secrets.SURGE_DOMAIN }} --token ${{secrets.SURGE_TOKEN }}
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
