# Source= https://angular.io/guide/testing**//
# Learn yaml file https://www.tutorialspoint.com/yaml/yaml_comments.htm
name: Continuous Integration of App
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm ci

      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

        # No 'uses' keyword because we want to run script from package.json file
      - name: Deployment in Action
        run: |
          npm i
          npm run deploy

        # Just demo to show how to read parameter with ${{}}
      - name: ${{github.workflow }}-${{github.ref }}
        run: dir

      - name: Deploy static files (Github page - into docs folder)
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        if: ${{ github.ref == 'refs/heads/main' }} # Only main branch
        with:
          github_token: ${{secrets.GITHUB_TOKEN}} # ???
          keep_files: true # Keeping existing files
          destination_dir: ./docs
          publish_dir: ./docs
          commit_message: ----> ${{github.event.head_commit.message}} # Set custom commit message
          # force_orphan: true # allows you to make your publish branch with only the latest commit
          #publish_branch: master # Set Another GitHub Pages Branch, but we want under foder docs!!
